baseURL = "http://www.kubernetes.cafe/"
languageCode = "en-us"
title = "Kubernetes Cafe"
theme = "hugo-cards"
builtBy = false

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[params]
  builtBy = "dgonzalez"
  defaultImage = "kubernetes.png"

  facebook = ""
  quora = ""
  twitter = "http://twitter.com/dagonzago"
  github = "http://github.com/dgonzalez"
  email = ""

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  analytics = "UA-22808190-2"
  disqus = ""

  [params.copyright]
     name = "David Gonzalez"
     link = "http://www.kubernetes.cafe/"

