version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run: 
          name: Installing dependencies
          command: |
            pip install pyopenssl
            export CLOUD_SDK_SITEPACKAGES=1
            echo $GCP_SERVICE_KEY_FILE_JSON | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project kubernetes-cafe
            gcloud --quiet config set compute/zone eu-west-1
            apt update
            apt install hugo
      - run:
          name: Init submodules
          command: git submodule init
      - run:
          name: Generate site
          command: hugo
      - run:
          name: Push site
          command: gsutil -m rsync -R  public gs://www.kubernetes.cafe
          
